# Generated by Django 3.2.6 on 2022-07-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_tag_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['value']},
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.TextField(db_index=True, max_length=100, unique=True),
        ),
    ]
